version: 2.1

executors:
  docker-node:
    docker:
      - image: circleci/node:latest

jobs:
  build-and-test:
    executor: docker-node
    steps:
      - checkout
      - run:
          name: install
          command: npm install

      - run:
          name: test
          command: npm test
          requires: install

workflows:
  build-and-deploy:
    jobs:
      - build
